import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Base.module.css'
import { useState, useEffect } from 'react'
import BlogList from '../../src/components/BlogList'
import { getBlogList } from '../../src/helpers/api'
import { type_blog } from '../../src/helpers/types'

export default function BlogPage() {
  const emptyBlogsList: type_blog[] = []
  const [blogList, setBlogList] = useState(emptyBlogsList)
  useEffect(() => {
    getBlogList().then((blogListData: type_blog[]) => setBlogList(blogListData))
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <BlogList blogList={blogList}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/assets/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
