import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Base.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const [counter, setCounter] = useState(3)
  const router = useRouter()
  if (router.pathname === '/') {
    const intvl = setInterval(() => setCounter(counter - 1), 1000)
    setTimeout(() => {
      clearInterval(intvl)
      router.push('/blog')
    }, 2800)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>

      <main className={styles.main}>
        You are at the default page, redirecting to blog list in {counter}...
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/assets/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
